apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-container
        image: yourdockerhub/train-schedule-app
        ports:
        - containerPort: 8080
